# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-app

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9b5c3217-3c89-4632-a188-a908194df630'
  imageRepository: 'snippets_restapi_dev'
  containerRegistry: 'snippetscontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Docker/postgres/Dockerfile'
  tag: '$(Build.BuildId)_dev'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure für Bildungseinrichtungen(f326e4c7-7827-4649-b4b1-e0719f776b2e)'
        azureContainerRegistry: '{"loginServer":"snippetscontainerregistry.azurecr.io", "id" : "/subscriptions/f326e4c7-7827-4649-b4b1-e0719f776b2e/resourceGroups/Snippets-RG/providers/Microsoft.ContainerRegistry/registries/SnippetsContainerRegistry"}'
        dockerComposeFile: '**/docker-compose_azure.yml'
        dockerComposeFileArgs: |
          POSTGRES_USER=snippets@snippets-db
          POSTGRES_PASSWORD=Asdf1234.
          POSTGRES_DB=postgres
          POSTGRES_HOST_NAME=snippets-db.postgres.database.azure.com
          REST_API_PORT=8010
        action: 'Build services'
        includeSourceTags: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure für Bildungseinrichtungen(f326e4c7-7827-4649-b4b1-e0719f776b2e)'
        azureContainerRegistry: '{"loginServer":"snippetscontainerregistry.azurecr.io", "id" : "/subscriptions/f326e4c7-7827-4649-b4b1-e0719f776b2e/resourceGroups/Snippets-RG/providers/Microsoft.ContainerRegistry/registries/SnippetsContainerRegistry"}'
        dockerComposeFile: '**/docker-compose_azure.yml'
        dockerComposeFileArgs: |
          POSTGRES_USER=snippets@snippets-db
          POSTGRES_PASSWORD=Asdf1234.
          POSTGRES_DB=postgres
          POSTGRES_HOST_NAME=snippets-db.postgres.database.azure.com
          REST_API_PORT=8010
        action: 'Push services'
        includeSourceTags: true