apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippets-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snippets-dev
  template:
    metadata:
      labels:
        app: snippets-dev
    spec:
      containers:
      - name: snippets-dev
        image: snippets_restapi
        ports:
        - containerPort: 8010
          name: snippets-rest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snippets-dev
  name: snippets-dev
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: snippets-dev
  type: LoadBalancer