steps:
  - name: "docker/compose:1.27.4"
    args: ["-f", "docker-compose_google.yml", "up", "-d", "--build"]
    id: '1.27.4'
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker tag snippets_db:latest eu.gcr.io/$PROJECT_ID/snippets_db:$TAG_NAME']
    wait_for: ['1.27.4']
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ['-c', 'docker tag snippets_restapi:latest eu.gcr.io/$PROJECT_ID/snippets_restapi:$TAG_NAME']
    wait_for: ['1.27.4']
images:
  - "eu.gcr.io/$PROJECT_ID/snippets_db:$TAG_NAME"
  - "eu.gcr.io/$PROJECT_ID/snippets_restapi:$TAG_NAME"
