steps:
  - name: "docker/compose:1.27.4"
    args: ["up", "-d", "--build"]
  # re-tag images
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["tag", "snippets_db:latest eu.gcr.io/$PROJECT_ID/snippets_db:$TAG_NAME"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "snippet_pgadmin:latest eu.gcr.io/$PROJECT_ID/snippet_pgadmin:$TAG_NAME",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "snippet_restapi:latest eu.gcr.io/$PROJECT_ID/snippet_restapi:$TAG_NAME",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/snippets_db:$TAG_NAME"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/snippet_pgadmin:$TAG_NAME"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/snippet_restapi:$TAG_NAME"]
images:
  - "eu.gcr.io/$PROJECT_ID/snippets_db:$TAG_NAME"
  - "eu.gcr.io/$PROJECT_ID/snippet_pgadmin:$TAG_NAME"
  - "eu.gcr.io/$PROJECT_ID/snippet_restapi:$TAG_NAME"
