version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 105334670318.dkr.ecr.us-east-1.amazonaws.com)
      - ECR_REPOSITORY_URI_1="436760934442.dkr.ecr.eu-central-1.amazonaws.com/snippets_db"
      - ECR_REPOSITORY_URI_2="436760934442.dkr.ecr.eu-central-1.amazonaws.com/snippets_pgadmin"
      - ECR_REPOSITORY_URI_3="436760934442.dkr.ecr.eu-central-1.amazonaws.com/snippets_restapi"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - AWS_IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - now=$(date)
  build:
    commands:
      - echo Build started on $now with tag $AWS_IMAGE_TAG
      - echo Building the Docker image...
      - docker-compose -f docker-compose_aws.yml up -d --build
      - docker tag snippets_db:latest $ECR_REPOSITORY_URI_1:$AWS_IMAGE_TAG
      - docker tag snippets_db:latest $ECR_REPOSITORY_URI_1:latest
      - docker tag snippets_pgadmin:latest $ECR_REPOSITORY_URI_2:$AWS_IMAGE_TAG
      - docker tag snippets_pgadmin:latest $ECR_REPOSITORY_URI_2:latest
      - docker tag snippets_restapi:latest $ECR_REPOSITORY_URI_3:$AWS_IMAGE_TAG
      - docker tag snippets_restapi:latest $ECR_REPOSITORY_URI_3:latest
  post_build:
    commands:
      - echo Build completed on $now tag $AWS_IMAGE_TAG
      - echo Pushing the Docker images...
      - docker push $ECR_REPOSITORY_URI_1:$AWS_IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI_1:latest
      - docker push $ECR_REPOSITORY_URI_2:$AWS_IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI_2:latest
      - docker push $ECR_REPOSITORY_URI_3:$AWS_IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI_3:latest
      - rm docker-compose.yml
artifacts:
  files:
    - 'Dockerrun.aws.json'